version: '3.1'

services:
  backend:
    container_name: backend
    env_file:
      - .env
    networks:
      - network
    build:
      context: ./back
    ports:
      - "8000:8000"

networks:
  network:
    driver: bridge
