[package]
name = "back"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
jsonwebtoken = "9.3.0"
rand = "0.8"
base64 = "0.22.1"
lazy_static = "1.4.0"
diesel = { version = "2.1.0", features = ["postgres"] }
dotenvy = "0.15"
