# TODO read https://api.rocket.rs/v0.5/rocket_sync_db_pools/ and use env instead of this file
[global.databases.postgres_db]
url = "postgres://postgres_username:postgres_password@localhost:5432/postgres_name"